config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, controllers: { omniauth_callbacks: "callbacks", registrations: "registrations", passwords: "passwords", sessions: "sessions" }
  root to: 'pages#index'
  get '/about', to: 'pages#about'
  get '/events', to: 'pages#events'

  get '/request-email', to: 'users#request_email', as: 'request_email'

  resources :users, path: 'artists' do
    member do
      get :follow
      post :follow
      get :unfollow
      post :unfollow
    end
    collection do
      match 'search' => 'users#search', via: [:get, :post], as: :search
    end
  end

  get '/users', to: redirect('/artists')
  get '/feed', to: 'users#home', as: 'updates'

  resources :conversations do
    resources :messages
  end

  resources :posts, path: 'journal' do
    member do
      get :publishing, path: 'publish'
      post :publish
      get :unpublishing, path: 'unpublish'
      post :unpublish
      get :like
      post :like
      get :unlike
      post :unlike
    end
  end

  get "/artists/:id/user-activity" => 'users#activity', as: 'user_activity'
  get "/artists/:id/user-pages" => 'users#posts', as: 'user_posts'
  get "/artists/:id/user-artworks" => 'users#artworks', as: 'user_artworks'

  resources :tags

  resources :artworks do
    member do
      get :like
      post :like
      get :unlike
      post :unlike
    end
    collection do
      match 'search' => 'artworks#search', via: [:get, :post], as: :search
    end
  end

  resources :charges

  get 'notifications/:id/link_through', to: 'notifications#link_through', as: :link_through
  get 'notifications/mark_all_read', to: 'notifications#mark_all_read', as: :mark_all_read
  resources :notifications, only: :index

  namespace :admin do
    root to: 'users#index'
    resources :users
    resources :artworks
    resources :posts
    resources :wallpapers
  end
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :notified_by, class_name: 'User'
  belongs_to :user
  belongs_to :notifiable, polymorphic: true

  scope :unread, -> { where(read: false) }
  scope :read, -> { where(read: true) }

  def emoji
    if notifiable_type == 'Post'
      "📝"
    elsif notifiable_type == 'Artwork'
      "🖼"
    else
      "👋🏽"
    end
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :authenticate_user!

  def index
    @notifications = current_user.notifications.order('created_at desc')
  end

  def link_through
    @notification = Notification.find(params[:id])
    @notification.update read: true
    redirect_to @notification.notifiable
  end

  def mark_all_read
    current_user.notifications.unread.each do |n|
      n.update read: true
    end
  end
end

app/views/notifications/_notification.html.haml
%p.s-navbar__notification{class: ('s-navbar__notification__unread' unless notification.read)}
  - if notification.notifiable_type == 'User'
    %strong= link_to notification.notified_by.full_name, notification.notified_by
    = notification.action
    you
  - else
    = link_to notification.notified_by.full_name, notification.notified_by
    = notification.action
    your
    = notification.notifiable_type.downcase
    %strong= link_to notification.notifiable.label, link_through_path(notification)
  %br
  %span.u-small-text
    = notification.emoji
    = notification.created_at.to_formatted_s(:long)
%hr.u-black-line--thin

app/views/notifications/index.html.haml
.container
  .content
    %h2.u-center Notifications
    %hr.u-black-line--thin
    - @notifications.each do |notification|
      = render partial: 'notification', locals: { notification: notification }