config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, controllers: { omniauth_callbacks: "callbacks", registrations: "registrations", passwords: "passwords", sessions: "sessions" }
  root to: 'pages#index'
  get '/about', to: 'pages#about'
  get '/events', to: 'pages#events'

  get '/request-email', to: 'users#request_email', as: 'request_email'

  resources :users, path: 'artists' do
    member do
      get :follow
      post :follow
      get :unfollow
      post :unfollow
    end
    collection do
      match 'search' => 'users#search', via: [:get, :post], as: :search
    end
  end

  get '/users', to: redirect('/artists')
  get '/feed', to: 'users#home', as: 'updates'

  resources :conversations do
    resources :messages
  end

  resources :posts, path: 'journal' do
    member do
      get :publishing, path: 'publish'
      post :publish
      get :unpublishing, path: 'unpublish'
      post :unpublish
      get :like
      post :like
      get :unlike
      post :unlike
    end
  end

  get "/artists/:id/user-activity" => 'users#activity', as: 'user_activity'
  get "/artists/:id/user-pages" => 'users#posts', as: 'user_posts'
  get "/artists/:id/user-artworks" => 'users#artworks', as: 'user_artworks'

  resources :tags

  resources :artworks do
    member do
      get :like
      post :like
      get :unlike
      post :unlike
    end
    collection do
      match 'search' => 'artworks#search', via: [:get, :post], as: :search
    end
  end

  resources :charges

  get 'notifications/:id/link_through', to: 'notifications#link_through', as: :link_through
  get 'notifications/mark_all_read', to: 'notifications#mark_all_read', as: :mark_all_read
  resources :notifications, only: :index

  namespace :admin do
    root to: 'users#index'
    resources :users
    resources :artworks
    resources :posts
    resources :wallpapers
  end
end

app/views/shared/_activity.html.haml
- events.each do |event|
  .m-event
    .m-chat__message
      = link_to event.user do
        = profile_image(event.user, css_class: 'a-avatar--thumb-square')
      .m-chat__inbox-entry
        %p
          = link_to event.user.label, event.user
          = event.action
          = link_to event.eventable.label, event.eventable
        %p
          %span.m-chat__datestamp-large
            = relative_time(event.created_at)
            ago

    - if event.eventable_type == 'Post'
      = render partial: 'shared/events/post', locals: { post: event.eventable }

    - if event.eventable_type == 'User'
      = render partial: 'shared/events/user', locals: { user: event.eventable }

    - if event.eventable_type == 'Artwork'
      = render partial: 'shared/events/artwork', locals: { artwork: event.eventable }

app/views/shared/_artist_block.html.haml
= profile_image(user, css_class: 'a-avatar')
%br
%h1= link_to user.full_name, user
= render partial: 'shared/social_links', locals: { user: user }
.content.content--tight.u-center
  %p= sanitize user.bio
  #follower_count[user]= render partial: 'shared/follow_link', locals: { artist: user, user_list: true }

app/views/shared/_artworks.html.haml
.m-gallery
  - artworks.each do |artwork|
    .m-gallery__piece
      = link_to artwork do
        = image_tag artwork.image.url(:square_small)
        %h2= artwork.name

        .u-center#likes_count[artwork]= render partial: 'artworks/like_link', locals: { subject: artwork, user_list: true }

app/views/shared/_follow_link.html.haml
- if current_user
  - if current_user == artist
    %p
      %i.fa.fa-heart
      = artist_follower_count(artist) if defined?(user_list)
  - elsif user_follows_artist?(current_user, artist)
    %p
      = link_to unfollow_user_path(artist), class: 'a-love-link', remote: true do
        %i.fa.fa-heart
      = artist_follower_count(artist) if defined?(user_list)
  - else
    %p
      = link_to follow_user_path(artist), class: 'a-love-link', remote: true do
        %i.fa.fa-heart-o
      = artist_follower_count(artist) if defined?(user_list)
- else
  %p
    = link_to new_user_session_path, class: 'a-love-link' do
      %i.fa.fa-heart-o
    = artist_follower_count(artist) if defined?(user_list)

app/views/shared/_posts.html.haml
.m-stories
  - posts.each do |post|
    .m-story
      = link_to post do
        %img.m-story__image{src: post.image_preview}
      %h4.m-story__title
        = link_to post do
          = post_status(post)
          = link_to post.title, post
      = link_to post do
        %p.m-story__date= post_date(post)

app/views/shared/_social_links.html.haml
.a-icon-row
  - if user.website.present?
    %a{href: website_url(user), target: '_blank'}
      %i.fa.fa-globe
  - if user.instagram_username.present?
    %a{href: instagram_url(user), target: '_blank'}
      %i.fa.fa-instagram
  - if user.facebook_username.present?
    %a{href: facebook_url(user), target: '_blank'}
      %i.fa.fa-facebook
  - if user.twitter_username.present?
    %a{href: twitter_url(user), target: '_blank'}
      %i.fa.fa-twitter

app/views/shared/_tags.html.haml
.content
  .a-tags
    - tags.each do |tag|
      .a-tag= link_to tag.name, tag

app/views/shared/_user_list.html.haml
- users.each do |user|
  %h1= link_to user.full_name, user

app/views/shared/_wallpaper.html.haml
- content_for :additional_stylesheet do
  %style
    :plain
      #{selector} {
        background: linear-gradient(rgba(0, 0, 0, 0.4), rgba(0, 0, 0, 0.4) ), url(#{source.url(:small)});
        background-size: cover;
        background-attachment: fixed;
        background-repeat: no-repeat;
        background-position: left top;
      }

      @media all and (min-width: 900px) {
        #{selector} {
          background: linear-gradient(rgba(0, 0, 0, 0.4), rgba(0, 0, 0, 0.4) ), url(#{source.url(:medium)});
          background-size: cover;
          background-attachment: fixed;
          background-repeat: no-repeat;
          background-position: left top;
        }
      }

      @media all and (min-width: 1280px) {
        #{selector} {
          background: linear-gradient(rgba(0, 0, 0, 0.4), rgba(0, 0, 0, 0.4) ), url(#{source.url(:large)});
          background-size: cover;
          background-attachment: fixed;
          background-repeat: no-repeat;
          background-position: left top;
        }
      }