config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, controllers: { omniauth_callbacks: "callbacks", registrations: "registrations", passwords: "passwords", sessions: "sessions" }
  root to: 'pages#index'
  get '/about', to: 'pages#about'
  get '/events', to: 'pages#events'

  get '/request-email', to: 'users#request_email', as: 'request_email'

  resources :users, path: 'artists' do
    member do
      get :follow
      post :follow
      get :unfollow
      post :unfollow
    end
    collection do
      match 'search' => 'users#search', via: [:get, :post], as: :search
    end
  end

  get '/users', to: redirect('/artists')
  get '/feed', to: 'users#home', as: 'updates'

  resources :conversations do
    resources :messages
  end

  resources :posts, path: 'journal' do
    member do
      get :publishing, path: 'publish'
      post :publish
      get :unpublishing, path: 'unpublish'
      post :unpublish
      get :like
      post :like
      get :unlike
      post :unlike
    end
  end

  get "/artists/:id/user-activity" => 'users#activity', as: 'user_activity'
  get "/artists/:id/user-pages" => 'users#posts', as: 'user_posts'
  get "/artists/:id/user-artworks" => 'users#artworks', as: 'user_artworks'

  resources :tags

  resources :artworks do
    member do
      get :like
      post :like
      get :unlike
      post :unlike
    end
    collection do
      match 'search' => 'artworks#search', via: [:get, :post], as: :search
    end
  end

  resources :charges

  get 'notifications/:id/link_through', to: 'notifications#link_through', as: :link_through
  get 'notifications/mark_all_read', to: 'notifications#mark_all_read', as: :mark_all_read
  resources :notifications, only: :index

  namespace :admin do
    root to: 'users#index'
    resources :users
    resources :artworks
    resources :posts
    resources :wallpapers
  end
end

app/models/artwork.rb
class Artwork < ApplicationRecord
  belongs_to :artist, class_name: 'User'
  has_many :artwork_likes, dependent: :destroy
  has_many :fans, through: :artwork_likes, source: :user
  has_many :events, dependent: :destroy, foreign_key: :eventable_id
  has_many :notifications, dependent: :destroy, foreign_key: :notifiable_id

  extend FriendlyId
  friendly_id :name, use: [:slugged, :finders]

  mount_uploader :image, ArtworkUploader

  scope :curated, -> { where(curated: true) }
  scope :in_popularity_order, -> { order('artwork_likes_count desc') }

  def label
    name
  end

  def price_in_gbp
    price ? "£#{price}" : nil
  end
end

app/controllers/admin/artworks_controller.rb
class Admin::ArtworksController < Admin::BaseController
  before_action :get_artwork, only: [:update, :destroy]

  def index
    @artworks = Artwork.in_popularity_order
  end

  def update
    if @artwork.update(artwork_params)
      redirect_to admin_artworks_path, notice: 'Artwork successfully updated.'
    else
      redirect_to admin_artworks_path, notice: 'Artwork could not be updated.'
    end
  end

  def destroy
    @artwork.destroy
    redirect_to admin_artworks_path, notice: 'Artwork successfully deleted.'
  end

  private

  def get_artwork
    @artwork = Artwork.find(params[:id])
  end

  def artwork_params
    params[:artwork].permit(:name, :description, :image, :price, :frame_size, :curated)
  end
end

app/controllers/artworks_controller.rb
class ArtworksController < ApplicationController
  load_and_authorize_resource
  before_action :find_artwork, only: [:show, :like, :unlike]
  before_action :authenticate_user!, only: [:like]

  def show
    @artwork = Artwork.find(params[:id])
    @user = @artwork.artist
  end

  def search
    index
    render :index
  end

  def index
    @search = Artwork.curated.ransack(params[:q])
    @artworks = @search.result(distinct: true).in_popularity_order
    @artworks_wallpaper = Wallpaper.find_by(location: 'Artworks').image
  end

  def new
    @artwork = Artwork.new
  end

  def create
    @artwork = Artwork.new(artwork_params)
    @artwork.artist_id = current_user.id

    respond_to do |format|
      if @artwork.save
        current_user.events.create(action: 'listed', eventable: @artwork)
        format.html { redirect_to @artwork, notice: 'Artwork created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    if @artwork.update(artwork_params)
      respond_to do |format|
        format.html { redirect_to @artwork, notice: "We've updated your artwork." }
      end
    else
      respond_to do |format|
        format.html { render :edit }
      end
    end
  end

  def destroy
    @artwork.destroy
    respond_to do |format|
      format.html { redirect_to artworks_path }
    end
  end

  def like
    @artwork_like = ArtworkLike.where(user: current_user, artwork: @artwork).first_or_create
    @event = current_user.events.where(action: 'liked', eventable: @artwork).first_or_create
    @artwork.artwork_likes_count += 1
    create_artwork_like_notification(@artwork)
    render :likes
  end

  def unlike
    @artwork_like = ArtworkLike.where(user: current_user.id, artwork: @artwork).destroy_all
    @event = Event.where(user: current_user, eventable: @artwork).destroy_all
    @artwork.artwork_likes_count -= 1
    delete_artwork_like_notification(@artwork)
    render :likes
  end

  private

  def find_artwork
    @artwork = Artwork.find(params[:id])
  end

  def artwork_params
    params[:artwork].permit(:name, :description, :image, :price, :frame_size, :tags)
  end

  def create_artwork_like_notification(artwork)
    return if artwork.artist == current_user
    Notification.create(user: artwork.artist, notified_by: current_user, notifiable: artwork, action: 'liked')
  end

  def delete_artwork_like_notification(artwork)
    return if artwork.artist == current_user
    notification = Notification.find_by(user_id: artwork.artist.id, notified_by_id: current_user.id, notifiable_id: artwork.id, notifiable_type: 'Artwork')
    notification.destroy if notification.present?
  end
end

app/helpers/artwork_helper.rb
module ArtworkHelper
  def frame_size_options_for_select(selected = nil)
    sizes = ['18-32"', '33-47"', '48-62"']
    options_for_select(sizes.map { |s| s }, selected)
  end
end

app/views/admin/artworks/index.html.haml
.container
  .content.content--xxwide
    .m-admin-table__row
      .m-admin-table__column-20.u-center
        %h4 Name
      .m-admin-table__column-15.u-center
        %h4 Created
      .m-admin-table__column-20.u-center
        %h4 Size
      .m-admin-table__column-5.u-center
        %h4 Price
      .m-admin-table__column-5.u-center
        %h4
          %i.fa.fa-heart
      .m-admin-table__column-15.u-center
        %h4 Curated?
      .m-admin-table__column-20.u-center
    %hr.u-black-line
    - @artworks.each do |artwork|
      = form_for [:admin, artwork] do |f|
        .m-admin-table__row
          .m-admin-table__column-20.u-center
            = link_to artwork do
              = image_tag(artwork.image, class: 'm-admin-table__image')
              %p= artwork.name.present? ? artwork.name : 'Untitled artwork'
          .m-admin-table__column-15.u-center
            %p= artwork.created_at.to_date.to_formatted_s(:long)
          .m-admin-table__column-20.u-center
            %p= f.select :frame_size, frame_size_options_for_select(f.object.frame_size), { label: 'Size' }, onchange: "this.form.submit();"
          .m-admin-table__column-5.u-center
            %p
              = "£#{artwork.price}" if artwork.price
          .m-admin-table__column-5.u-center
            %p= artwork.fans.size
          .m-admin-table__column-15.u-center
            %p= f.check_box :curated, onchange: "this.form.submit();"
          .m-admin-table__column-20.u-center
            %p= link_to 'Edit', edit_artwork_path(artwork), class: 'a-button'