config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, controllers: { omniauth_callbacks: "callbacks", registrations: "registrations", passwords: "passwords", sessions: "sessions" }
  root to: 'pages#index'
  get '/about', to: 'pages#about'
  get '/events', to: 'pages#events'

  get '/request-email', to: 'users#request_email', as: 'request_email'

  resources :users, path: 'artists' do
    member do
      get :follow
      post :follow
      get :unfollow
      post :unfollow
    end
    collection do
      match 'search' => 'users#search', via: [:get, :post], as: :search
    end
  end

  get '/users', to: redirect('/artists')
  get '/feed', to: 'users#home', as: 'updates'

  resources :conversations do
    resources :messages
  end

  resources :posts, path: 'journal' do
    member do
      get :publishing, path: 'publish'
      post :publish
      get :unpublishing, path: 'unpublish'
      post :unpublish
      get :like
      post :like
      get :unlike
      post :unlike
    end
  end

  get "/artists/:id/user-activity" => 'users#activity', as: 'user_activity'
  get "/artists/:id/user-pages" => 'users#posts', as: 'user_posts'
  get "/artists/:id/user-artworks" => 'users#artworks', as: 'user_artworks'

  resources :tags

  resources :artworks do
    member do
      get :like
      post :like
      get :unlike
      post :unlike
    end
    collection do
      match 'search' => 'artworks#search', via: [:get, :post], as: :search
    end
  end

  resources :charges

  get 'notifications/:id/link_through', to: 'notifications#link_through', as: :link_through
  get 'notifications/mark_all_read', to: 'notifications#mark_all_read', as: :mark_all_read
  resources :notifications, only: :index

  namespace :admin do
    root to: 'users#index'
    resources :users
    resources :artworks
    resources :posts
    resources :wallpapers
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :creator, class_name: 'User'

  has_many :post_tags
  has_many :posts, through: :post_tags

  extend FriendlyId
  friendly_id :name, use: [:slugged, :finders]
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  load_and_authorize_resource
  before_action :find_tag, only: [:show]

  def index
    @tags = Tag.all
  end

  def new
    @tag = Tag.new
  end

  def create
    @tag = Tag.new(tag_params)
    @tag.creator = current_user

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, notice: "We've added your tag to the list." }
      else
        format.html { render :new, notice: "Sorry, there was an issue creating the #{@tag.name} tag." }
      end
    end
  end

  def update
    if @tag.update(tag_params)
      respond_to do |format|
        format.html { redirect_to @tag, notice: "We've updated the #{@tag.name} tag." }
      end
    else
      respond_to do |format|
        format.html { render :edit, notice: "Sorry, there was an issue updating the #{@tag.name} tag." }
      end
    end
  end

  def destroy
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to tags_path }
    end
  end

  private

  def find_tag
    @tag = Tag.find(params[:id])
  end

  def tag_params
    params[:tag].permit(:name, :description)
  end
end

app/views/tags/_form.html.haml
.container
  = form_for @tag do |f|
    .content
      %h2 Tag name
      = f.text_field :name, class: 'u-full-width'
    .content.content--wide
      = cktext_area :tag, :description, cols: 40, ckeditor: { uiColor: '$colour-grey', toolbar: 'mini' }

    .content.content--wide
      .a-buttons.u-float-right
        = @tag.persisted? ? (link_to 'Cancel', @tag, class: 'a-button' ) : (link_to 'Cancel', tags_path, class: 'a-button' )
        = f.submit 'Save', class: 'a-button'

app/views/tags/index.html.haml
.container
  .content
    %h1 Tags
    = link_to 'Create a tag', new_tag_path, class: 'a-button a-button--corner'  if can? :create, Tag
  .content
    = render partial: 'shared/tags', locals: { tags: @tags }

app/views/tags/show.html.haml
.container
  .content
    %h1= @tag.name
    = link_to 'Edit', edit_tag_path(@tag), class: 'a-button a-button--corner' if can? :edit, @tag
    = sanitize @tag.description

  - if @tag.posts.published.any?
    .content
      = render partial: 'shared/posts', locals: { posts: @tag.posts.published, title: "Related posts" }